### PR TITLE
add case with no form and only User object.

### PR DESCRIPTION
**Pull request by deepNeuralNick**
added this case because some django backends are not supporting native forms and could be used only as REST API's. My change does not change anything in the current functionality of the project, just extends it.

### CODE REVIEW

**Comment by logginst** [comment]
Just seconding this change as I ran into the same use case.

**Comment by deepNeuralNick** [comment]
> Just seconding this change as I ran into the same use case.

i found another solution to the user verification problem, if you are not in a hurry you can wait for the PR to be merged by the repo owner if he ever sees it :100:

**Comment by foo290** [comment]
lol, sorry, I'll make some time on this weekend and do some code cleanup and feature updates including this PR

**Comment by deepNeuralNick** [comment]
is this gonna be merged sometime? @foo290

**Comment by mariogiampieri** [comment]
Bumping this- thanks first off for the amazing package and secondly for this PR!

**Comment by deepNeuralNick** [comment]
Hi! i am doing a cleanup on my account, is this gonna be merged @foo290 , looks like some people are also waiting for this feature as per the comments in this PR.

**Comment by mariogiampieri** [comment]
Thanks @foo290 !

**Pull request merged**
